name: 下载文件
on:
    workflow_dispatch:
jobs:
    downloadFile:
      runs-on: windows-latest
      steps:
        - name: make a dir
          run: mkdir upload
        - name: download file
          run: |
            cd upload
            curl -o telegram.exe https://td.telegram.org/tx64/tsetup-x64.5.13.1.exe
        - name: upload file
          uses: actions/upload-artifact@v4
          with:
            name: upload
            path: upload
